// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUZE-9S9t79GHEdMplS2bMfPpMRpa4QpQ',
    appId: '1:750957916790:web:2e69a3f054ff6f33de6557',
    messagingSenderId: '750957916790',
    projectId: 'apple-sign-in-afd6e',
    authDomain: 'apple-sign-in-afd6e.firebaseapp.com',
    storageBucket: 'apple-sign-in-afd6e.firebasestorage.app',
    measurementId: 'G-C7R2W6ER6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLbNflx6McCfRi3ilPK2OK-Bbpl9KGT5A',
    appId: '1:750957916790:android:582fe3aac5daa932de6557',
    messagingSenderId: '750957916790',
    projectId: 'apple-sign-in-afd6e',
    storageBucket: 'apple-sign-in-afd6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3UwWfBlB-b87Sb4NVEdDT4YWvFcVc8zw',
    appId: '1:750957916790:ios:31f66890bf193e50de6557',
    messagingSenderId: '750957916790',
    projectId: 'apple-sign-in-afd6e',
    storageBucket: 'apple-sign-in-afd6e.firebasestorage.app',
    iosBundleId: 'com.example.appleSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3UwWfBlB-b87Sb4NVEdDT4YWvFcVc8zw',
    appId: '1:750957916790:ios:31f66890bf193e50de6557',
    messagingSenderId: '750957916790',
    projectId: 'apple-sign-in-afd6e',
    storageBucket: 'apple-sign-in-afd6e.firebasestorage.app',
    iosBundleId: 'com.example.appleSignin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUZE-9S9t79GHEdMplS2bMfPpMRpa4QpQ',
    appId: '1:750957916790:web:0f355624784eb5f3de6557',
    messagingSenderId: '750957916790',
    projectId: 'apple-sign-in-afd6e',
    authDomain: 'apple-sign-in-afd6e.firebaseapp.com',
    storageBucket: 'apple-sign-in-afd6e.firebasestorage.app',
    measurementId: 'G-GEVGVCKWBM',
  );
}
